/**
 * Generates src/environments/environment.ts and environment.development.ts
 * from .env files. Selection rules:
 *   1. Load .env (defaults).
 *   2. Overlay .env.<NODE_ENV> (e.g. .env.production) when present.
 *   3. Process env vars override file values.
 * No .env values are committed to the generated file other than what is
 * already present in .env / .env.<NODE_ENV>; nothing is hard-coded.
 */
const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

const projectRoot = path.join(__dirname, '..');

function loadEnvFile(name) {
  const file = path.join(projectRoot, name);
  if (!fs.existsSync(file)) return {};
  return dotenv.parse(fs.readFileSync(file));
}

const cliProd = process.argv.includes('--prod') || process.argv.includes('--production');
const nodeEnv = cliProd ? 'production' : process.env.NODE_ENV || 'development';
const baseEnv = loadEnvFile('.env');
const overlayEnv = loadEnvFile(`.env.${nodeEnv}`);
const merged = { ...baseEnv, ...overlayEnv, ...process.env };

const isProduction = (merged.NODE_ENV || nodeEnv) === 'production';
const apiUrl = merged.API_URL;

if (!apiUrl) {
  console.error('[set-env] API_URL is not defined. Add it to .env or .env.' + nodeEnv);
  process.exit(1);
}

const fileBody = `// AUTO-GENERATED by scripts/set-env.js. Do not edit by hand.
export const environment = {
  production: ${isProduction},
  apiUrl: '${apiUrl}',
};
`;

const outDir = path.join(projectRoot, 'src', 'environments');
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

fs.writeFileSync(path.join(outDir, 'environment.ts'), fileBody);
fs.writeFileSync(path.join(outDir, 'environment.development.ts'), fileBody);

console.log(
  `[set-env] mode=${isProduction ? 'production' : 'development'} apiUrl=${apiUrl}`,
);
